In [25]:
import pandas as pd
from engine import load_env, create_engine_from_env
from models.manufacture_module import get_manufacturer_df, get_active_unique_manufacturers, get_manufacturer_bulletins_json, print_bulletin_details, convert_bulletin_to_df, save_vehicle_models_to_csv, batch_save_manufacturer_models, search_models_by_description

In [26]:
import json
from typing import Union, Any

def parse_json_string(json_string: str) -> Union[dict, list]:
    """
    Parse a JSON string into a Python object (dict or list).

    Args:
        json_string (str): A valid JSON string.

    Returns:
        dict or list: Parsed JSON object.

    Raises:
        ValueError: If the input is not valid JSON.
        TypeError: If input is not a string.
    """
    if not isinstance(json_string, str):
        raise TypeError("Input must be a JSON string")

    try:
        return json.loads(json_string)
    except json.JSONDecodeError as exc:
        raise ValueError(f"Invalid JSON string: {exc}") from exc

In [27]:

# Loaded environment variables and created database engine
load_env()
engine = create_engine_from_env()

In [28]:

# Batch save vehicle models for specified manufacturers
# manufactures = ["Hyundai","Honda","Kia","Mazda","Subaru","Toyota","Volkswagen"]
# manufactures = ["Mitsubishi"]
# batch_save_manufacturer_models(engine, manufactures)

In [29]:

model_number_db = pd.read_csv("db/db_vehicle_models.csv")

In [24]:
make_df = model_number_db[model_number_db["Manufacturer"] == "Mitsubishi"]

In [10]:



# make_df[
    
#     (make_df["ModelYear"]==2026)
#     # (1==1)
#     &(make_df["Description"].str.contains("CX-30", case=False, na=False))
#     # & (make_df["Description"].str.contains("Cross", case=False, na=False))
#     # & (make_df["Description"].str.contains("noir", case=False, na=False))
#     & (make_df["Package"]=="KE00")
#     ]

In [54]:
make_df[
        (make_df["ModelYear"]==2025)
        & make_df["Description"].str.contains("outlander", case=False, na=False)
        & make_df["Description"].str.contains("gt", case=False, na=False)
        & make_df["Description"].str.contains("phev", case=False, na=False)
    ]

,Manufacturer,ModelYear,ModelNumber,Description,Description2,Package,Style_ID
3449,Mitsubishi,2025,COEV-X,Outlander PHEV GT S-AWC,NaN,NaN,459716

In [76]:

make = "Mitsubishi"
year = 2025
keywords = ["eclipse"]
keywords = ['outlander','gt', 'prem']
# keywords =  ['rvr', 'es', "fwd"]
# keywords = ["black"]

search_models_by_description(make, year, keywords)

,Manufacturer,ModelYear,ModelNumber,Description,Description2,Package,Style_ID
3444,Mitsubishi,2025,CO45-X,Outlander GT Premium S-AWC,NaN,NaN,470586